services:
  - type: web
    name: g-clinic
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    region: oregon
    pythonVersion: 3.11
